default:
    just --list

install-dev-deps:
    #!/usr/bin/env bash
    pip install -r $HOME/dotfiles/python/dev-requirements.pip

format:
    #!/usr/bin/env bash
    cd {{invocation_directory()}}
    isort $(git ls-files -s '*.py')
    python -m reindent -r -n $(git ls-files '*.py')
    black .

lint:
    #!/usr/bin/env bash
    cd {{invocation_directory()}}
    flake8 $(git ls-files '*.py')
